CREATE TABLE `users`(
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL,
    `username` VARCHAR(50) NOT NULL,
    `password` VARCHAR(200) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `roles`(
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET= utf8mb4;

CREATE TABLE `users_roles`(
    `user_id` BIGINT NOT NULL,
    `role_id` BIGINT NOT NULL,
    PRIMARY KEY(user_id,role_id),
    KEY FK_ROLE_idx(role_id),

    CONSTRAINT `FK_ROLE_01` FOREIGN KEY (role_id)
        REFERENCES roles(id)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT `FK_USER` FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;